# Data Analysis with Pandas

## video games sales

Anas Abusaif
25/oct/2021

In [229]:
import pandas as pd
data_frame = pd.read_csv('./vgsales.csv')
data_frame

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [230]:
# most common Publisher
most_common_publisher=data_frame['Publisher'].mode()[0]

In [231]:
# most common platform
most_common_platform=data_frame['Platform'].mode()[0]

In [232]:
# most common genre
most_common_genre=data_frame['Genre'].mode()[0]

In [233]:
# top 20 highest grossing games
top_twenty_highest_grossing_games=data_frame[['Rank','Name']].head(20)
top_twenty_highest_grossing_games

    Rank                                          Name
0      1                                    Wii Sports
1      2                             Super Mario Bros.
2      3                                Mario Kart Wii
3      4                             Wii Sports Resort
4      5                      Pokemon Red/Pokemon Blue
5      6                                        Tetris
6      7                         New Super Mario Bros.
7      8                                      Wii Play
8      9                     New Super Mario Bros. Wii
9     10                                     Duck Hunt
10    11                                    Nintendogs
11    12                                 Mario Kart DS
12    13                   Pokemon Gold/Pokemon Silver
13    14                                       Wii Fit
14    15                                  Wii Fit Plus
15    16                            Kinect Adventures!
16    17                            Grand Theft Auto V
17    18                 Grand Theft Auto: San Andreas
18    19                             Super Mario World
19    20  Brain Age: Train Your Brain in Minutes a Day

In [234]:
# median for north american sales
na_median_sales=data_frame['NA_Sales'].median()

In [235]:
# ten games surrounding the median sales output
five_above=data_frame[data_frame.NA_Sales>na_median_sales].tail(5)
five_below=data_frame[data_frame.NA_Sales<na_median_sales].head(5)
ten_median_na_seller_names=pd.concat([five_above,five_below])
ten_median_na_seller_names

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10975,10977,Fighting Fantasy: The Warlock of Firetop Mountain,DS,2009.0,Role-Playing,Aspyr,0.09,0.00,0.00,0.01,0.09
10990,10992,I Love Puppies,DS,2010.0,Simulation,Destineer,0.09,0.00,0.00,0.01,0.09
10999,11001,Cake Mania: Main Street,DS,2011.0,Simulation,Majesco Entertainment,0.09,0.00,0.00,0.01,0.09
11003,11005,DaGeDar,DS,2011.0,Action,GameMill Entertainment,0.09,0.00,0.00,0.01,0.09
11012,11014,NERF N-Strike: Double Blast Bundle,Wii,2010.0,Shooter,Electronic Arts,0.09,0.00,0.00,0.00,0.09
137,138,World of Warcraft,PC,2004.0,Role-Playing,Activision,0.07,6.21,0.00,0.00,6.28
214,215,Monster Hunter Freedom 3,PSP,2010.0,Role-Playing,Capcom,0.00,0.00,4.87,0.00,4.87
338,339,Friend Collection,DS,2009.0,Misc,Nintendo,0.00,0.00,3.67,0.00,3.67
348,349,Pro Evolution Soccer 2008,PS2,2007.0,Sports,Konami Digital Entertainment,0.05,0.00,0.64,2.93,3.63
383,384,Monster Hunter 4,3DS,2013.0,Role-Playing,Capcom,0.00,0.00,3.44,0.00,3.44

In [236]:
# standerd deviations between the mean and the top grossing
standered=data_frame.NA_Sales.std()
mean_=data_frame.NA_Sales.mean()
rows=data_frame.index.stop
std1=rows*0.3413
std2=(rows-std1)*0.1359
std3=(rows-std1-std2)*0.0214
std4=(rows-std1-std2-std3)*0.00013
data_frame
def standered_from_mean(rank):
  rank_=data_frame.Rank.head()[rank]
  if rank_ < std4:
    return 3
  if rank_<std3:
    return 2
  if rank_<std2:
    return 1
  if rank_<std1:
    return 0
standered_from_mean(0)

3

In [237]:
data_frame[['Platform','Global_Sales']].groupby('Platform').mean()

          Global_Sales
Platform
2600          0.729925
3DO           0.033333
3DS           0.486169
DC            0.307115
DS            0.380254
GB            2.606633
GBA           0.387470
GC            0.358561
GEN           1.050370
GG            0.040000
N64           0.686144
NES           2.561939
NG            0.120000
PC            0.269604
PCFX          0.030000
PS            0.610920
PS2           0.581046
PS3           0.720722
PS4           0.827679
PSP           0.244254
PSV           0.149952
SAT           0.194162
SCD           0.311667
SNES          0.837029
TG16          0.080000
WS            0.236667
Wii           0.699404
WiiU          0.572448
X360          0.774672
XB            0.313422
XOne          0.662254

In [238]:
def test():

    def assert_equal(actual,expected):
        assert actual == expected, f"Expected {expected} but got {actual}"

    assert_equal(most_common_publisher, 'Electronic Arts')
    assert_equal(most_common_platform, 'DS')
    assert_equal(most_common_genre, 'Action')
    assert_equal(top_twenty_highest_grossing_games.iloc[0].Name, 'Wii Sports')
    assert_equal(top_twenty_highest_grossing_games.iloc[19].Name, 'Brain Age: Train Your Brain in Minutes a Day')
    assert_equal(na_median_sales, 0.08)
    assert_equal(ten_median_na_seller_names.iloc[0].Name, 'Fighting Fantasy: The Warlock of Firetop Mountain')

    print("Success!!!")

test()

Success!!!